DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;



CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username VARCHAR UNIQUE,
name VARCHAR,
email VARCHAR UNIQUE,
date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
password_hash VARCHAR
);

CREATE TABLE posts (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title VARCHAR,
content TEXT,
author VARCHAR,
date_posted DATETIME DEFAULT CURRENT_TIMESTAMP,
slug VARCHAR,
users_id INTEGER REFERENCES users(id)
)
